name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required for pushing to the gh-pages branch

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "arunandholly27@gmail.com"
          git config --global user.name "arunandholly27"
      - name: Checkout Code
        uses: [actions/checkout@v4](https://github.com)

      - name: Setup Node.js
        uses: [actions/setup-node@v4](https://github.com)
        with:
          node-version: '20' # Use the version matching your local environment
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build -- --configuration production --base-href /book-walk-frontend/

      - name: Deploy to GitHub Pages
        uses: [JamesIves/github-pages-deploy-action@v4](https://github.com)
        with:
          folder: dist/book-walk-app # Path to your build output
          branch: gh-pages