name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Install SSH Key
        uses: [shimataro/ssh-key-action](https://github.com/marketplace/actions/install-ssh-key)@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy
        run: npm run deploy
        with:
          GH_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}